### ISSUE TITLE
Levantamento de requisitos[modelos]

### ISSUE THREAD

**Issue by ramonrdm** [thiagobrez/registroDeAccs#1]
Este software é real e será usado como base para um sistema oficial do Curso Letras Libras, sendo assim atenção e responsabilidade neste projeto.
Olhar a descrição oficial:
[ATIVIDADES_COMPLEMENTARES_atualizada_2010.pdf](https://github.com/thiagobrez/registroDeAccs/files/949691/ATIVIDADES_COMPLEMENTARES_atualizada_2010.pdf)

Modelos:
ACCs
 - Titulo
 - TipoAtividade
 - Horas
 - Aluno
 - ISSNouISBN
 - Data
 - Local
 - Relatório
 - ArquivoAnexado
 - LinkExterno
Usuário
 - Padrão Django

Aluno
 - Matricula
 - Nome
 - e-mail

Esses são os modelos básicos mínimos, caso vejam necessidade de mais dados, acrescentem.

**Comment by thiagobrez** [comment]
Quase pronto, houve um problema ao adicionar o atributo ISSN ou ISBN que ainda não consegui resolver.
Erro: django.db.utils.IntegrityError: NOT NULL constraint failed

**Comment by thiagobrez** [comment]
Banco de dados recriado. Funcionando corretamente.
