### ISSUE TITLE
Levantamento de requisitos[funcionalidades]

### ISSUE THREAD

**Issue by ramonrdm** [thiagobrez/registroDeAccs#4]
+ CRUD de ACCs, alunos e usuários dentro do admin django, sendo assim necessita login.
 + Lista de ACCs, uma página que pode ser consultado ACCs por nome ou matricula do aluno, sem login.

**Comment by ramonrdm** [comment]
Fazer busca de ACCs no Admin
Colocar tipos de atividades de ACCs e seus códigos
ISSN ou ISBN obrigatório.

**Comment by ramonrdm** [comment]
Data da emissão deve ser igual ou superior a data do curso.

**Comment by thiagobrez** [comment]
Todas as issues concluídas.
